apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: An example of a Backstage application.
  labels:
    system: web-apps
  tags:
    - javascript
    - react
  annotations:
    jenkins.io/github-folder: 'briandesousa/backstage-sample-service'
spec:
  type: service
  lifecycle: experimental
  owner: avinash
