name: Backstage


on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Octo Organization
      
      - name: Run Backstage
        uses: github/backstage@v
        env: 
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
